name: manual

on:
  push:
    branches:
      - manual

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout manual
        uses: actions/checkout@v2
        with:
          ref: manual

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.62.2'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public